const nodes = [
  //   Pink Container 1
  {
    id: "A",
    type: "output",
    position: { x: -425, y: 200 },
    data: null,
    style: {
      width: 250,
      height: 100,
      backgroundColor: "#ffbbffff",
      border: "1px solid #f898f8",
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  {
    id: "A-1",
    data: { label: "vSmart2" },
    position: { x: 180, y: 10 },
    parentNode: "A",
    extent: "parent",
    // draggable: false,
    style: {
      width: 60,
      height: 60,
      backgroundColor: "#b0ffb0",
      border: "1px solid #b0ffb0",
      borderRadius: "10px",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "A-2",
    data: { label: "vSmart1" },
    position: { x: 10, y: 10 },
    parentNode: "A",
    extent: "parent",
    // draggable: false,
    style: {
      width: 60,
      height: 60,
      backgroundColor: "#ffffae",
      border: "1px solid #ffe6cc",
      borderRadius: "10px",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "A-3",
    data: { label: "SITE 251" },
    position: { x: 95, y: 15 },
    parentNode: "A",
    extent: "parent",
    draggable: false,
    style: {
      width: 60,
      color: "#fff",
      padding: "2px 5px",
      backgroundColor: "#3498db",
      border: "none",
      borderRadius: "4px",
      boxShadow: "none",
      outline: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "A-4",
    data: { label: "10.1.1.0/24" },
    position: { x: 87, y: 40 },
    parentNode: "A",
    extent: "parent",
    draggable: false,
    style: {
      width: 75,
      padding: "2px 5px",
      backgroundColor: "#ffffff",
      border: "1px solid #eeeeee",
      borderRadius: "4px",
      boxShadow: "none",
      outline: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },

  {
    id: "B",
    type: "output",
    data: { label: "SW" },
    position: { x: -350, y: 350 },
    style: {
      width: 60,
      backgroundColor: "#fff",
    },
  },
  {
    id: "B-1",
    data: null,
    position: { x: 60, y: 15 },
    parentNode: "B",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      //   height: 50,
      backgroundColor: "transparent",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "B-2",
    // data: { label: "temp" },
    data: null,
    position: { x: 13, y: 0 },
    parentNode: "B",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      //   height: 50,
      backgroundColor: "transparent",
    },
    sourcePosition: "top",
    targetPosition: "top",
  },
  {
    id: "B-3",
    data: null,
    position: { x: 43, y: 0 },
    parentNode: "B",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      //   height: 50,
      backgroundColor: "transparent",
    },
    sourcePosition: "top",
    targetPosition: "top",
  },

  //   Pink Container 2
  {
    id: "A_1",
    type: "output",
    position: { x: 325, y: 200 },
    data: { label: "Dummy" },
    style: {
      width: 250,
      height: 100,
      backgroundColor: "#ffbbffff",
      border: "1px solid #f898f8",
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  {
    id: "A_1-1",
    data: { label: "vSmart2" },
    position: { x: 180, y: 10 },
    parentNode: "A_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 60,
      height: 60,
      backgroundColor: "#b0ffb0",
      border: "1px solid #b0ffb0",
      borderRadius: "10px",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "A_1-2",
    data: { label: "vSmart1" },
    position: { x: 10, y: 10 },
    parentNode: "A_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 60,
      height: 60,
      backgroundColor: "#ffffae",
      border: "1px solid #ffe6cc",
      borderRadius: "10px",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "A_1-3",
    data: { label: "SITE 252" },
    position: { x: 95, y: 15 },
    parentNode: "A_1",
    extent: "parent",
    draggable: false,
    style: {
      width: 60,
      color: "#fff",
      padding: "2px 5px",
      backgroundColor: "#3498db",
      border: "none",
      borderRadius: "4px",
      boxShadow: "none",
      outline: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "A_1-4",
    data: { label: "10.1.2.0/24" },
    position: { x: 87, y: 40 },
    parentNode: "A_1",
    extent: "parent",
    draggable: false,
    style: {
      width: 75,
      padding: "2px 5px",
      backgroundColor: "#ffffff",
      border: "1px solid #eeeeee",
      borderRadius: "4px",
      boxShadow: "none",
      outline: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },

  {
    id: "B_1", // pink container 2 - sw
    type: "output",
    data: { label: "SW" },
    position: { x: 400, y: 350 },
    style: {
      width: 60,
      backgroundColor: "#fff",
    },
  },
  {
    id: "B_1-1",
    data: null,
    position: { x: -3, y: 17 },
    parentNode: "B_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      backgroundColor: "transparent",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "B_1-2",
    // data: { label: "temp" },
    data: null,
    position: { x: 13, y: 0 },
    parentNode: "B_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      //   height: 50,
      backgroundColor: "transparent",
    },
    sourcePosition: "top",
    targetPosition: "top",
  },
  {
    id: "B_1-3",
    data: null,
    position: { x: 43, y: 0 },
    parentNode: "B_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      //   height: 50,
      backgroundColor: "transparent",
    },
    sourcePosition: "top",
    targetPosition: "top",
  },

  //   Blue Container 1
  {
    id: "C_1",
    type: "output",
    position: { x: -200, y: 400 },
    data: null,
    style: {
      width: 150,
      height: 200,
      backgroundColor: "#cae4ff",
      border: "1px solid #5191d1",
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  {
    id: "C_1-1",
    data: { label: "vEdge-1" },
    position: { x: 40, y: 30 },
    parentNode: "C_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
    },
    sourcePosition: "top",
    targetPosition: "top",
  },
  {
    id: "C_1-1-1",
    data: null,
    position: { x: 23, y: 17 },
    parentNode: "C_1-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      height: 1,
      backgroundColor: "transparent",
      border: "none",
      outline: "none",
      boxShadow: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "C_1-2",
    data: { label: "Host-1" },
    position: { x: 40, y: 130 },
    parentNode: "C_1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
    },
  },
  {
    id: "C_1-3",
    data: { label: "SITE 11" },
    position: { x: 95, y: 173 },
    parentNode: "C_1",
    extent: "parent",
    draggable: false,
    style: {
      width: 60,
      backgroundColor: "#3498db",
      color: "#fff",
      padding: "2px 0px",
      border: "none",
      outline: "none",
      boxShadow: "none",
    },
  },
  //   Blue Container 2
  {
    id: "C_2",
    type: "output",
    position: { x: 0, y: 400 },
    data: null,
    style: {
      width: 150,
      height: 200,
      backgroundColor: "#cae4ff",
      border: "1px solid #5191d1",
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  {
    id: "C_2-1",
    data: { label: "vEdge-2" },
    position: { x: 40, y: 30 },
    parentNode: "C_2",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
    },
    sourcePosition: "top",
    targetPosition: "top",
  },
  {
    id: "C_2-1-1",
    data: null,
    position: { x: 23, y: 17 },
    parentNode: "C_2-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      height: 1,
      backgroundColor: "transparent",
      border: "none",
      outline: "none",
      boxShadow: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "C_2-2",
    data: { label: "Host-2" },
    position: { x: 40, y: 130 },
    parentNode: "C_2",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
    },
  },
  {
    id: "C_2-3",
    data: { label: "SITE 13" },
    position: { x: 95, y: 170 },
    parentNode: "C_2",
    extent: "parent",
    draggable: false,
    style: {
      width: 60,
      backgroundColor: "#3498db",
      color: "#fff",
      padding: "2px 5px",
      border: "none",
      outline: "none",
      boxShadow: "none",
    },
  },
  //   Blue Container 3
  {
    id: "C_3",
    type: "output",
    position: { x: 200, y: 400 },
    data: null,
    style: {
      width: 150,
      height: 200,
      backgroundColor: "#cae4ff",
      border: "1px solid #5191d1",
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  {
    id: "C_3-1",
    data: { label: "vEdge-3" },
    position: { x: 40, y: 30 },
    parentNode: "C_3",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
    },
    sourcePosition: "top",
    targetPosition: "top",
  },
  {
    id: "C_3-1-1",
    data: null,
    position: { x: 23, y: 17 },
    parentNode: "C_3-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      height: 1,
      backgroundColor: "transparent",
      border: "none",
      outline: "none",
      boxShadow: "none",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "C_3-2",
    data: { label: "Host-3" },
    position: { x: 40, y: 130 },
    parentNode: "C_3",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
    },
  },
  {
    id: "C_3-3",
    data: { label: "SITE 12" },
    position: { x: 95, y: 170 },
    parentNode: "C_3",
    extent: "parent",
    draggable: false,
    style: {
      width: 60,
      backgroundColor: "#3498db",
      color: "#fff",
      padding: "2px 5px",
      border: "none",
      outline: "none",
      boxShadow: "none",
    },
  },
  //   Black Container
  {
    id: "D",
    type: "output",
    position: { x: -150, y: -0 },
    data: null,
    style: {
      width: 450,
      height: 220,
      backgroundColor: "#c9c9c9",
      border: "1px solid #c9c9c9",
      borderRadius: "10px",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  {
    id: "D-1",
    data: null,
    position: { x: 50, y: 10 },
    parentNode: "D",
    extent: "parent",
    // draggable: false,
    style: {
      width: 350,
      height: 100,
      backgroundColor: "#ffdcb9",
      border: "1px solid #eba968",
      borderRadius: "10px",
    },
  },
  {
    id: "D-1-0",
    data: { label: "vManage-0" },
    position: { x: 130, y: 5 },
    parentNode: "D-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 90,
      backgroundColor: "#fff",
    },
  },
  {
    id: "D-1-0-1",
    data: null,
    position: { x: 0, y: 25 },
    parentNode: "D-1-0",
    extent: "parent",
    draggable: false,
    style: {
      width: 0,
      padding: 0,
      height: 0,
      // border: "none",
      outline: "none",
      backgroundColor: "#fff",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "D-1-0-2",
    data: null,
    position: { x: 89, y: 25 },
    parentNode: "D-1-0",
    extent: "parent",
    draggable: false,
    style: {
      width: 0,
      padding: 0,
      height: 0,
      outline: "none",
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "D-1-1",
    data: { label: "vManage-1" },
    position: { x: 5, y: 30 },
    parentNode: "D-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 90,
      outline: "none",
      boxShadow: "none",
      backgroundColor: "#fff",
    },
  },
  {
    id: "D-1-1-1",
    data: null,
    position: { x: 88, y: 25 },
    parentNode: "D-1-1",
    extent: "parent",
    draggable: false,
    style: {
      width: 0,
      padding: 0,
      height: 0,
      outline: "none",
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "D-1-1-2",
    data: null,
    position: { x: 88, y: 15 },
    parentNode: "D-1-1",
    extent: "parent",
    draggable: false,
    style: {
      width: 0,
      padding: 0,
      height: 0,
      outline: "none",
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "D-1-2",
    data: { label: "vManage-2" },
    position: { x: 130, y: 60 },
    parentNode: "D-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 90,
      backgroundColor: "#fff",
    },
  },
  {
    id: "D-1-2-1",
    data: null,
    position: { x: 43, y: 35 },
    parentNode: "D-1-2",
    extent: "parent",
    // draggable: false,
    style: {
      width: 0,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  {
    id: "D-1-3",
    data: { label: "vManage-3" },
    position: { x: 255, y: 30 },
    parentNode: "D-1",
    extent: "parent",
    // draggable: false,
    style: {
      width: 90,
      boxShadow: "none",
      border: "none",
      backgroundColor: "#fff",
    },
  },
  {
    id: "D-1-3-1",
    data: null,
    position: { x: 0, y: 25 },
    parentNode: "D-1-3",
    extent: "parent",
    // draggable: false,
    style: {
      width: 0,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "D-1-3-2",
    data: null,
    position: { x: 0, y: 15 },
    parentNode: "D-1-3",
    extent: "parent",
    // draggable: false,
    style: {
      width: 0,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "D-2",
    data: null,
    position: { x: 13, y: 120 },
    parentNode: "D",
    extent: "parent",
    // draggable: false,
    style: {
      width: 425,
      height: 50,
      backgroundColor: "#84d7ff",
      border: "1px solid #2d8bb8",
      borderRadius: "10px",
    },
  },
  {
    id: "D-2-1",
    data: { label: "vBond-1" },
    position: { x: 10, y: 7 },
    parentNode: "D-2",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
      //   height: 50,
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "D-2-2",
    data: { label: "vBond-2" },
    position: { x: 345, y: 7 },
    parentNode: "D-2",
    extent: "parent",
    // draggable: false,
    style: {
      width: 70,
      //   height: 50,
      backgroundColor: "#fff",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "D-3",
    data: { label: "SW" },
    position: { x: 195, y: 180 },
    parentNode: "D",
    extent: "parent",
    // draggable: false,
    style: {
      width: 60,
      backgroundColor: "#fff",
    },
  },
  {
    id: "D-3-1",
    data: null,
    position: { x: 0, y: 25 },
    parentNode: "D-3",
    extent: "parent",
    draggable: false,
    style: {
      width: 1,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "D-3-2",
    data: null,
    position: { x: 60, y: 15 },
    parentNode: "D-3",
    extent: "parent",
    draggable: false,
    style: {
      width: 1,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "D-3-3",
    data: null,
    position: { x: 0, y: 5 },
    parentNode: "D-3",
    extent: "parent",
    draggable: false,
    style: {
      width: 1,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "left",
    targetPosition: "left",
  },
  {
    id: "D-3-4",
    data: null,
    position: { x: 60, y: 5 },
    parentNode: "D-3",
    extent: "parent",
    draggable: false,
    style: {
      width: 1,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  {
    id: "D-3-5",
    data: null,
    position: { x: 29, y: 0 },
    parentNode: "D-3",
    extent: "parent",
    draggable: false,
    style: {
      width: 1,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "top",
    targetPosition: "top",
  },
  {
    id: "D-3-6",
    data: null,
    position: { x: 60, y: 25 },
    parentNode: "D-3",
    extent: "parent",
    draggable: false,
    style: {
      width: 1,
      height: 0,
      padding: 0,
      backgroundColor: "#fff",
    },
    sourcePosition: "right",
    targetPosition: "right",
  },
  //   Viptela Images Version Container
  {
    id: "E",
    type: "output",
    position: { x: 400, y: 70 },
    data: { label: "CA" },
    style: {
      width: 60,
      backgroundColor: "#fff",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    sourcePosition: "bottom",
    targetPosition: "left",
  },
  {
    id: "E-1",
    data: null,
    position: { x: 30, y: 35 },
    parentNode: "E",
    extent: "parent",
    // draggable: false,
    style: {
      width: 1,
      padding: 0,
      //   height: 50,
      backgroundColor: "transparent",
    },
    sourcePosition: "bottom",
    targetPosition: "bottom",
  },
  //   Cloud Version Container
  {
    id: "F_1",
    type: "output",
    position: { x: 450, y: 150 },
    data: { label: "Physical_LAN" },
    style: {
      width: 80,
      backgroundColor: "#fff",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    sourcePosition: "right",
  },
  //   Internet / MPLS Cloud
  {
    id: "G",
    type: "output",
    position: { x: -40, y: 280 },
    data: { label: "Internet / MPLS Cloud" },
    style: {
      width: 200,
      backgroundColor: "#19cbb1",
      border: "1px solid #19cbb1",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    targetPosition: "left",
  },
  //   Internet / MPLS Cloud 1
  {
    id: "G_1",
    type: "output",
    // position: { x: 0, y: 320 },
    position: { x: -40, y: 280 },
    data: { label: "Internet / MPLS Cloud" },
    style: {
      width: 200,
      backgroundColor: "#19cbb1",
      border: "1px solid #19cbb1",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    targetPosition: "right",
  },
  // Resource Req container
  {
    id: "H",
    type: "resource-container",
    position: { x: 375, y: 525 },
    data: {
      label: "",
      content: [
        "Resource Requirement:",
        "CPU: 24 Virtual Cores",
        "RAM: 64GB (min)",
      ],
    },
    // data: null,
    draggable: false,
    style: {
      width: 150,
      height: 50,
      // backgroundColor: "#19cbb1",
      // backgroundColor: "transparent",
      // border: "1px solid #19cbb1",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  // Content Container 1
  {
    id: "I",
    type: "resource-container",
    position: { x: 340, y: 0 },
    data: {
      label: "",
      content: [
        "Viptela Images version: 20.3.2",
        "IOS-XE version: 17.03.02",
        "Windows Server 2019",
      ],
    },
    // data: null,
    draggable: false,
    style: {
      width: 200,
      height: 50,
      // backgroundColor: "#19cbb1",
      // backgroundColor: "transparent",
      // border: "1px solid #19cbb1",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
];

export default nodes;
